<?php

namespace AppBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLastGame()
    {

        $query = $this->createQueryBuilder('g')
                      ->orderBy('g.id', 'DESC')
                      ->setMaxResults(3)
                      ->getQuery();

        return $query->getResult();
    }


   




    public function getLastSevenGame()
    {

        $query = $this->createQueryBuilder('g')
                      ->orderBy('g.id', 'DESC')
                      ->setMaxResults(7)
                      ->getQuery();

        return $query->getResult();
    }
}
