<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLastReservation()
    {

        $query = $this->createQueryBuilder('r')


            ->orderBy('r.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        return $query->getResult();
    }
}
